readme:
	pdflatex READ_ME_FIRST.tex
	pdflatex READ_ME_FIRST.tex
	pdflatex READ_ME_FIRST.tex

install:
	pdflatex InstallAnaconda.tex
	pdflatex InstallAnaconda.tex
	pdflatex InstallAnaconda.tex


clean:
	rm READ_ME_FIRST.aux READ_ME_FIRST.log READ_ME_FIRST.pdf
