readme:
	pdflatex READ_ME_FIRST.tex
	pdflatex READ_ME_FIRST.tex
	pdflatex READ_ME_FIRST.tex

schedule:
	pdflatex schedule.tex
	pdflatex schedule.tex
	pdflatex schedule.tex

install:
	pdflatex InstallAnaconda.tex
	pdflatex InstallAnaconda.tex
	pdflatex InstallAnaconda.tex

TA:
	pdflatex TeachingAssistants.tex
	pdflatex TeachingAssistants.tex
	pdflatex TeachingAssistants.tex

clean:
	rm READ_ME_FIRST.aux READ_ME_FIRST.log READ_ME_FIRST.pdf
